# Generated by Django 5.1.5 on 2026-10-08 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("when", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.CharField(max_length=60)),
                ("action", models.CharField(max_length=40)),
                ("details", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-when"],
            },
        ),
        migrations.CreateModel(
            name="AuthorizedCaller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="שם")),
                (
                    "phone",
                    models.CharField(max_length=20, unique=True, verbose_name="טלפון"),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="קוד אישי (ספרות)"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="פעיל")),
            ],
        ),
        migrations.CreateModel(
            name="LessonSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="מספר שיעור"
                    ),
                ),
                ("start", models.TimeField(verbose_name="התחלה")),
                ("end", models.TimeField(verbose_name="סיום")),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="NonSchoolDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="שם (חופשה / חג)"),
                ),
                ("date_from", models.DateField(verbose_name="מתאריך")),
                ("date_to", models.DateField(verbose_name="עד תאריך")),
            ],
            options={
                "ordering": ["date_from"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="שם הכיתה"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="סדר"),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        default="בית הספר", max_length=120, verbose_name="שם בית הספר"
                    ),
                ),
                (
                    "yemot_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="מספר מערכת ימות המשיח"
                    ),
                ),
                ("yemot_password_enc", models.TextField(blank=True)),
                (
                    "phone_dir",
                    models.CharField(
                        blank=True,
                        help_text="למשל /7 - אותה שלוחה שהגדרתם עם type=api",
                        max_length=60,
                        verbose_name="תיקיית השלוחה בימות המשיח (לשמירת הקלטות שמות)",
                    ),
                ),
                (
                    "caller_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="זיהוי יוצא לצינתוקים (אופציונלי)",
                    ),
                ),
                (
                    "voice_template_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="מזהה תבנית קמפיין להודעה קולית (אופציונלי)",
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("open", "כל מי שמתקשר/ת (מספר זהות בלבד)"),
                            ("phone", "רק מספרי טלפון רשומים"),
                            ("phone_pin", "מספר טלפון רשום + קוד אישי"),
                        ],
                        default="open",
                        max_length=12,
                        verbose_name="זיהוי המתקשר/ת",
                    ),
                ),
                (
                    "unknown_tz",
                    models.CharField(
                        choices=[
                            ("reject", "הודעת שגיאה אחרי 3 ניסיונות, בלי לשמור"),
                            (
                                "record",
                                "לשמור את הדיווח כ'תלמידה לא מזוהה' לטיפול המזכירה",
                            ),
                        ],
                        default="record",
                        max_length=8,
                        verbose_name="מספר זהות לא מוכר",
                    ),
                ),
                (
                    "ask_time",
                    models.BooleanField(
                        default=False,
                        verbose_name="לשאול בטלפון איזו שעה לרשום באיחור לבית ספר (אחרת - השעה הנוכחית)",
                    ),
                ),
                (
                    "ask_reason",
                    models.BooleanField(default=True, verbose_name="לשאול סיבה בחיסור"),
                ),
                (
                    "allow_other_date",
                    models.BooleanField(
                        default=True,
                        verbose_name="לאפשר דיווח חיסור למחר/אתמול/כמה ימים",
                    ),
                ),
                (
                    "days_off",
                    models.CharField(
                        default="4,5",
                        help_text="מספרי ימים: 0=שני ... 4=שישי, 5=שבת, 6=ראשון",
                        max_length=20,
                        verbose_name="ימים שלא נספרים (שבוע)",
                    ),
                ),
                (
                    "school_year_start",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="תחילת שנת הלימודים (לספירת 'שנה')",
                    ),
                ),
                ("support_code_hash", models.CharField(blank=True, max_length=128)),
                ("support_code_expires", models.DateTimeField(blank=True, null=True)),
                (
                    "support_contact",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="דרך ליצירת קשר עם התמיכה",
                    ),
                ),
            ],
            options={
                "verbose_name": "הגדרות",
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="שם ההתראה")),
                ("active", models.BooleanField(default=True, verbose_name="פעילה")),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("late_any", "איחורים (לבית ספר + לשיעור)"),
                            ("late_school", "איחורים לבית ספר"),
                            ("late_lesson", "איחורים לשיעור"),
                            ("absent_any", "ימי חיסור (כולם)"),
                            ("absent_unjustified", "ימי חיסור לא מוצדקים"),
                        ],
                        max_length=20,
                        verbose_name="מה סופרים",
                    ),
                ),
                (
                    "threshold",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="מספר (סף)"
                    ),
                ),
                (
                    "repeat",
                    models.BooleanField(
                        default=False,
                        verbose_name="חוזרת בכל כפולה של הסף (7, 14, 21...)",
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        choices=[
                            ("last_days", "X ימים אחרונים"),
                            ("month", "החודש הלועזי הנוכחי"),
                            ("week", "השבוע (מיום ראשון)"),
                            ("school_year", "מתחילת שנת הלימודים"),
                            ("custom", "טווח תאריכים קבוע"),
                        ],
                        default="last_days",
                        max_length=12,
                        verbose_name="טווח זמן",
                    ),
                ),
                (
                    "window_days",
                    models.PositiveSmallIntegerField(
                        default=183, verbose_name="מספר ימים (ל'X ימים אחרונים')"
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "notify_site",
                    models.BooleanField(
                        default=True, verbose_name="להציג במסך ההתראות באתר"
                    ),
                ),
                (
                    "notify_caller",
                    models.BooleanField(
                        default=True,
                        verbose_name="להשמיע למתקשרת בשיחה הבאה על התלמידה",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        default="לתלמידה יש {late} איחורים ו-{absent} ימי חיסור",
                        help_text="אפשר להשתמש ב: {name} {late} {absent} {count}",
                        max_length=250,
                        verbose_name="נוסח ההודעה בטלפון",
                    ),
                ),
                (
                    "tzintuk",
                    models.BooleanField(default=False, verbose_name="לשלוח צינתוק"),
                ),
                (
                    "tzintuk_voice",
                    models.BooleanField(
                        default=False, verbose_name="במקום צלצול - שיחה עם הקראת ההודעה"
                    ),
                ),
                (
                    "tzintuk_target",
                    models.CharField(
                        choices=[
                            ("contacts", "טלפוני ההורים/התלמידה המסומנים"),
                            ("extra", "מספרים נוספים בלבד"),
                            ("both", "שניהם"),
                        ],
                        default="contacts",
                        max_length=10,
                        verbose_name="למי לצנתק",
                    ),
                ),
                (
                    "extra_phones",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="מספרים נוספים (מופרדים בפסיק)",
                    ),
                ),
                (
                    "class_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.schoolclass",
                        verbose_name="רק לכיתה (ריק = כולן)",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tz",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="מספר זהות"
                    ),
                ),
                ("first_name", models.CharField(max_length=40, verbose_name="שם פרטי")),
                ("last_name", models.CharField(max_length=40, verbose_name="שם משפחה")),
                ("active", models.BooleanField(default=True, verbose_name="פעילה")),
                (
                    "name_recorded",
                    models.BooleanField(default=False, verbose_name="שם מוקלט בטלפון"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="הערות"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="attendance.schoolclass",
                        verbose_name="כיתה",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "school_class__order",
                    "school_class__name",
                    "last_name",
                    "first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=30, verbose_name="תיאור (אמא / אבא / תלמידה...)"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="טלפון")),
                (
                    "receives_alerts",
                    models.BooleanField(
                        default=True, verbose_name="מקבל/ת צינתוקי התראה"
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="קוד אישי לטלפון (ספרות)"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="attendance.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_tz",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="ת.ז. שהוקשה (לא מזוהה)"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("late_school", "איחור לבית ספר"),
                            ("late_lesson", "איחור לשיעור"),
                            ("absent", "חיסור"),
                        ],
                        max_length=12,
                        verbose_name="סוג",
                    ),
                ),
                ("date", models.DateField(verbose_name="תאריך")),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="עד תאריך (חיסור למספר ימים)",
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True, verbose_name="שעה")),
                (
                    "lesson",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="שיעור"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sick", "מחלה"),
                            ("approved", "אישור"),
                            ("other", "אחר"),
                            ("", "ללא"),
                        ],
                        max_length=10,
                        verbose_name="סיבה",
                    ),
                ),
                ("justified", models.BooleanField(default=False, verbose_name="מוצדק")),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, verbose_name="טופל (בדיווח לא מזוהה)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("phone", "טלפון"), ("web", "אתר")],
                        default="phone",
                        max_length=6,
                    ),
                ),
                ("caller_phone", models.CharField(blank=True, max_length=20)),
                (
                    "source_ref",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiple", models.PositiveSmallIntegerField(default=1)),
                ("count", models.PositiveSmallIntegerField()),
                ("message", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("window_start", models.DateField()),
                ("announce_pending", models.BooleanField(default=False)),
                ("announced_at", models.DateTimeField(blank=True, null=True)),
                ("handled", models.BooleanField(default=False, verbose_name="טופל")),
                ("tzintuk_status", models.CharField(blank=True, max_length=200)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="attendance.alertrule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["handled", "-created_at"],
            },
        ),
    ]
