# Generated by Django 5.1.5 on 2026-10-08 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool", models.CharField(max_length=40)),
                ("args", models.JSONField()),
                ("summary", models.CharField(max_length=400)),
                ("status", models.CharField(default="pending", max_length=10)),
                ("result", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="assistant_key_enc",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="assistant_model",
            field=models.CharField(
                default="claude-sonnet-5-5",
                max_length=60,
                verbose_name="מודל של העוזר האישי",
            ),
        ),
    ]
