# Generated by Django 5.1.5 on 2026-10-08 14:01

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_assistant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="שם בית הספר")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "ממתין לאישור"),
                            ("active", "פעיל"),
                            ("suspended", "מושעה"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "phone_secret",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=60, unique=True
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=80, verbose_name="איש קשר"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="טלפון"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="מייל"),
                ),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("last_report_at", models.DateTimeField(blank=True, null=True)),
                ("owner_notes", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"base_manager_name": "all_objects"},
        ),
        migrations.AlterModelOptions(
            name="pendingaction",
            options={"base_manager_name": "all_objects"},
        ),
        migrations.AlterModelManagers(
            name="alert",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="alertrule",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="attendance",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="auditlog",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="authorizedcaller",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="lessonslot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nonschoolday",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pendingaction",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schoolclass",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="schoolsettings",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="student",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="extension_done",
            field=models.BooleanField(
                default=False, verbose_name="השלוחה הוגדרה בימות המשיח"
            ),
        ),
        migrations.AlterField(
            model_name="authorizedcaller",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="טלפון"),
        ),
        migrations.AlterField(
            model_name="authorizedcaller",
            name="pin",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="קוד אישי (מגובב)"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pin",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="קוד אישי (מגובב)"
            ),
        ),
        migrations.AlterField(
            model_name="lessonslot",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="מספר שיעור"),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="name",
            field=models.CharField(max_length=40, verbose_name="שם הכיתה"),
        ),
        migrations.AlterField(
            model_name="student",
            name="tz",
            field=models.CharField(max_length=12, verbose_name="מספר זהות"),
        ),
        migrations.AddField(
            model_name="alert",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="authorizedcaller",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="nonschoolday",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorizedcaller",
            constraint=models.UniqueConstraint(
                fields=("school", "phone"), name="uniq_caller_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonslot",
            constraint=models.UniqueConstraint(
                fields=("school", "number"), name="uniq_lesson_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="uniq_class_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("school", "tz"), name="uniq_tz_per_school"
            ),
        ),
        migrations.AddField(
            model_name="schooluser",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="schooluser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
