# Generated by Django 5.1.5 on 2026-10-08 20:28

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_school_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("late_start", "התחלת לימודים מאוחרת"),
                            ("early_end", "סיום לימודים מוקדם"),
                            ("exam", "מבחן"),
                            ("trip", "טיול / פעילות"),
                            ("event", "אירוע אחר"),
                        ],
                        default="event",
                        max_length=10,
                        verbose_name="סוג",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="כותרת")),
                ("date_from", models.DateField(verbose_name="מתאריך")),
                ("date_to", models.DateField(verbose_name="עד תאריך")),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="שעה (התחלה מאוחרת / סיום מוקדם)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="הערות"),
                ),
                (
                    "announce_banner",
                    models.BooleanField(default=True, verbose_name="להציג כהודעה באתר"),
                ),
                (
                    "announce_phone",
                    models.BooleanField(
                        default=True, verbose_name="להשמיע בטלפון למי שמתקשרת"
                    ),
                ),
            ],
            options={
                "ordering": ["date_from", "kind"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=10)),
                ("recipients", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=200)),
                ("text", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="lessonslot",
            options={"ordering": ["number", "season"]},
        ),
        migrations.RemoveConstraint(
            model_name="lessonslot",
            name="uniq_lesson_per_school",
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="season",
            field=models.CharField(
                choices=[("all", "כל השנה"), ("winter", "חורף"), ("summer", "קיץ")],
                default="all",
                max_length=6,
                verbose_name="מערכת",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="candle_minutes",
            field=models.PositiveSmallIntegerField(
                default=18, verbose_name="הדלקת נרות: דקות לפני השקיעה"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="city_key",
            field=models.CharField(
                default="jerusalem", max_length=30, verbose_name="עיר (לזמני היום)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="custom_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="קו רוחב (מותאם אישית)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="custom_lon",
            field=models.FloatField(
                blank=True, null=True, verbose_name="קו אורך (מותאם אישית)"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="end_summer",
            field=models.TimeField(
                blank=True, null=True, verbose_name="סיום לימודים בקיץ"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="end_winter",
            field=models.TimeField(
                blank=True, null=True, verbose_name="סיום לימודים בחורף"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="friday_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="סיום לימודים ביום שישי"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="season_mode",
            field=models.CharField(
                choices=[
                    ("auto", "אוטומטי לפי שעון הקיץ הרשמי"),
                    ("winter", "תמיד מערכת חורף"),
                    ("summer", "תמיד מערכת קיץ"),
                ],
                default="auto",
                max_length=8,
                verbose_name="מערכת שעות קיץ/חורף",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="start_summer",
            field=models.TimeField(
                blank=True, null=True, verbose_name="תחילת לימודים בקיץ"
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="start_winter",
            field=models.TimeField(
                blank=True, null=True, verbose_name="תחילת לימודים בחורף"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonslot",
            constraint=models.UniqueConstraint(
                fields=("school", "number", "season"),
                name="uniq_lesson_per_school_season",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="class_filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.schoolclass",
                verbose_name="רק לכיתה (ריק = כולן)",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="school",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="attendance.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="messagelog",
            name="school",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="attendance.school",
            ),
        ),
    ]
